### ISSUE TITLE
Postproc not running for extra runs (run-01, run-02)

### ISSUE THREAD

**Issue by macwoodburn** [cohenlabUNC/clpipe#252] opened 2022-07-20 18:53 UTC
The function postproc (original postproc) is not running for files named as extra runs. 
For context, I'm running this:
fmri_postprocess -config_file /proj/cohenlab/projects/MAP/clpipe_config_maptasks_062022.json -submit 0011 -task emot

The file sub-0011_ses-01_task-emot_acq-AP_space-MNI152NLin2009cAsym_desc-preproc_bold_postproc.nii.gz is output by postproc (and accompanying csv file). However, postproc does not output the postprocessed files of multiple runs that were successfully preprocessed like sub-0011_ses-01_task-emot_acq-PA_run-1, and sub-0011_ses-01_task-emot_acq-PA_run-2. This is observed with all my subjects. I have run through postproc in prior versions of clpipe/fmriprep without this issue. Is the postproc function in this latest clpipe version not flexible to read file names?

Fmriprep version 21.0.2
Longleaf Environment:
module use /proj/hng/software/modules
module add clpipe

**Comment by wasciutto** [comment] 2022-07-21 14:40
Hi Mac, thanks for posting this issue. No, none of the changes made since v1.4 have impacted fmri_postprocess. I can debug the command you're running and see what's going on.

**Comment by wasciutto** [comment] 2022-07-21 15:23
```ERROR:root:local variable 'target_json' referenced before assignment
Traceback (most recent call last):
  File "/proj/hng/software/venvs/clpipe/clpipe-1.5.0/lib/python3.6/site-packages/clpipe/fmri_postprocess.py", line 175, in _fmri_postprocess_subject
    _fmri_postprocess_image(config, image, task,  tr, beta_series, tps_drop)
  File "/proj/hng/software/venvs/clpipe/clpipe-1.5.0/lib/python3.6/site-packages/clpipe/fmri_postprocess.py", line 203, in _fmri_postprocess_image
    image_json_path = _find_json(config, file)
  File "/proj/hng/software/venvs/clpipe/clpipe-1.5.0/lib/python3.6/site-packages/clpipe/fmri_postprocess.py", line 497, in _find_json
    logging.debug(target_json)
UnboundLocalError: local variable 'target_json' referenced before assignment```

This step is failing to find the .json files associated with your images - you can use the -TR flag to manually provide this value as a workaround

**Comment by wasciutto** [comment] 2022-11-15 22:14
Closing - with the -TR flag work-around, and postproc2 imminently replacing this command, the issue is not worth fixing at this moment

**Closed by wasciutto** 2022-11-15 22:14 UTC
Labels: bug, wontfix
